import Head from "next/head";
import Hero from "../components/Hero";
import Search from "../components/Search";
import { getAllMessages } from "../prisma/message";

const Homepage = ({ messages }) => {
  return (
    <div>
      <Head>
        <title>Among Us Only | Secret Message for Loved One Stay Secret</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Search messages={messages} />
    </div>
  );
}

export const getServerSideProps = async ({ req }) => {
  const messages = await getAllMessages();

  // Convert the updatedAt and createdAt in each user to string
  // Otherwise, Next.js will throw an error
  // Not required if you are not using the date fields

  const updatedMessages = messages.map((message) => ({
    ...message,
    updatedAt: message.updatedAt.toString(),
    createdAt: message.createdAt.toString(),
  }));

  return { props: { messages: updatedMessages } };
};

Homepage.layout = "PUBLIC";
export default Homepage;